site_name: MySpeed Documentation
site_url: https://myspeed.gnmyt.dev
site_description: MySpeed is a self-hosted speedtest analysis software that stores the speed of your internet for up to 30 days.
site_author: Mathias Wagner
copyright: Copyright &copy; 2021 - 2023 Mathias Wagner

repo_name: MySpeed
repo_url: https://github.com/gnmyt/myspeed
edit_uri: https://github.com/gnmyt/myspeed/edit/development/docs

plugins:
  - i18n:
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
        - locale: de
          name: Deutsch
          nav_translations:
            Start: Startseite
            Frequently Asked Questions: Häufig gestellte Fragen
            Setup: Einrichtung
            Guides: Anleitungen
            Configuring a Reverse Proxy: Einrichten eines Reverse Proxys
            Troubleshooting: Fehlerbehebung
            Instructions: Anweisungen
            The Interface: Die Benutzeroberfläche
            Settings: Einstellungen

theme:
  name: material
  logo: assets/images/logo.png
  features:
    - toc.integrate
    - content.code.annotate
    - content.code.copy
  favicon: assets/images/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      schema: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gnmyt/myspeed
    - icon: fontawesome/solid/heart
      link: https://ko-fi.com/gnmyt
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/germannewsmaker
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/386242172632170496

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Start: index.md
  - Frequently Asked Questions: faq.md
  - Setup:
      - Linux: setup/linux.md
      - Windows: setup/windows.md
  - Guides:
      - Configuring a Reverse Proxy: guides/reverse-proxy.md
  - Troubleshooting: troubleshooting.md
  - Instructions:
      - The Interface: instructions/main.md
      - Settings: instructions/settings.md
